name: Build and Deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Test
        run: echo "Testler çalıştırılıyor..."
      - name: Build Docker
        run: docker build . -t appointment-app
